### ISSUE TITLE
How To Parse The KDH Key Token?

### ISSUE THREAD

**Issue by cjh123456** [clover/clover-tr34-host#1]
Hello, may I ask how to parse the KDH Key Token returned by KDH?

**Comment by satur9nine** [comment]
In the tests here there is a test case that exercises KDH key token generation, KRD verification and decryption.

Here is a link https://github.com/clover/clover-tr34-host/blob/25e3ead11895b1cbc46e5dad76abdf3d61d51745/src/test/java/com/clover/tr34/Tr34CloverTest.java#L61

**Comment by cjh123456** [comment]
Sorry, perhaps I didn't describe my question accurately. My question is: How does KRD parse the TwoPassKeyToken returned by KDH (in CMS format), extracting the temporary key ciphertext, target key ciphertext (TR-34), signature content, signature algorithm, signature attributes, etc.?

**Comment by cjh123456** [comment]
For example, how to parse the following CMS data (from TR34-2012 Appendix B.9-KT KDH – The KDH Key Token) to extract signedData, encapContentInfo, recipientInfos, signerInfo, SignedAttributes, etc.?"

-----BEGIN KTKDH_2Pass PEM File-----
MIIGdQYJKoZIhvcNAQcCoIIGZjCCBmICAQExDTALBglghkgBZQMEAgEwggJoBgkq
hkiG9w0BBwOgggJZBIICVQIBADGCAZ4wggGaAgEAMEowQTELMAkGA1UEBhMCVVMx
FTATBgNVBAoTDFRSMzQgU2FtcGxlczEbMBkGA1UEAxMSVFIzNCBTYW1wbGUgQ0Eg
S1JEAgU0AAAABzBFBgkqhkiG9w0BAQcwODANBglghkgBZQMEAgEFADAYBgkqhkiG
9w0BAQgwCwYJYIZIAWUDBAIBMA0GCSqGSIb3DQEBCQQABIIBACy9CG3HIyhtl6ph
fB6UmA5Tmui/UakmxV/khYvkgIVlBvCPAJMn4urIE9d8eySgrlIyXFZFL3UEZs1X
ge8ctLVzpgckEG0SUvGMJ0IpWZt4h7o3nFCBeCGY3JoJRJPTicqD1vCNWNiOlUgG
97AKYgsgymB5BnRyfHnXS3ngOcmF4vEHvsMKf8guXNQmihos1Xn8gizDZqVy3GmV
JqGxzAzj9oMK5/6qK+FGTxv7SBTZePYAdkZAfyJLdYQPlhEn7w4jRyajajZWSjLS
x0YFpQhJyb+fk/cn0axo/tcg3u7SrQoGSzCsAdK+6zzNA9RjFdQPH/1tJg3G9lN9
cOAoGKcwga0GCSqGSIb3DQEHATCBnwYIKoZIhvcNAwcECAEjRWeJq83vgIGIUzKh
+EUh3i07I+vjyy1nSxYRTsWYIUECw97hdcKmaUAOsDkTbmMuSjIUCqtVRqxHh5n3
t6AlM19FzKPNGJQxT/UT4+Alc621E134sdsyd9neJz3GqLXnnSFfY7k6UhN9uvvl
zD/0cpGdhtJAl2I3D6gKd67Rg+HtWXv5v9ydKGk0x8Hh6NAD+6GCAdgwggHUMIG9
AgEBMA0GCSqGSIb3DQEBCwUAMEExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxUUjM0
IFNhbXBsZXMxGzAZBgNVBAMTElRSMzQgU2FtcGxlIENBIEtESBcNMTAxMTAyMTcz
MzMwWhcNMTAxMjAyMTczMzMwWjBIMBYCBTQAAAAIFw0xMDExMDIxNzI4MTNaMBYC
BTQAAAAKFw0xMDExMDIxNzMxNDZaMBYCBTQAAAALFw0xMDExMDIxNzMzMjVaMA0G
CSqGSIb3DQEBCwUAA4IBAQA28Go8iKy8+p+OOwhQ7uCanPe1spGIblENNJ/l8Fwb
232fOeTqZQiCjy7T7nljyFh0UnlcOUYrBg1blyyae174kKGTxXIl0ciNVu7R0D9+
mnWHDWBNFeAS/9e4UG6kuhTntRAYwW2NnvtqxcUVaGsTThax1n8ei/Q8j8mmC5YU
rczpr2nCepRT1CY0T2sURQ7lg4IUdB6r9/h/FSqTGfrZ7TtIGhE8AzY9Ka3QLjAx
Oik6/Bh7clKY+xTF2ZeWeFomzBnPB8K8miO49vbuGaAHkE9L9jLc/efygl8xL+Yo
49DHHNULsI7kBOKl8BGgtatPKmEnXiUAna4AZg7/MtbDMYICBDCCAgACAQEwSjBB
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMVFIzNCBTYW1wbGVzMRswGQYDVQQDExJU
UjM0IFNhbXBsZSBDQSBLREgCBTQAAAAGMAsGCWCGSAFlAwQCAaCBjjAYBgkqhkiG
9w0BCQMxCwYJKoZIhvcNAQcDMCAGCiqGSIb3DQEJGQMxEgQQFn6w5yeB5JQBEiM0
RVZneDAfBgkqhkiG9w0BBwExEgQQQTAyNTZLMFRCMDBFMDAwMDAvBgkqhkiG9w0B
CQQxIgQgXZgUXiL8t/Z1GxpFOjDFJIf5JLx170bbeXTHqmxLxy0wDQYJKoZIhvcN
AQEBBQAEggEAl7/Onxfx07p5Wr8kUygKPaCP95ooB4YETOBO/sbUwfVPbw4JOCIa
dAWsziEZH6yGuZgQMju3O0AE+13d4KqsKtBDHw3tPovPlXUKPVwmszOu+DDn7pok
tHAFJTcuDS2fJArGp20gKUunplG2KIIumhpkg6ZckxEoBDxxxp3Cp1GB1Hh5IMyD
XYwhEJiVuilVlYYDNhH3jtw9SFbSwft8bSXBybP9Ck5cK05gbWFAErl4qLWMKI/Q
4Wb/jVYQdLTzSXr9tGi7Cyd1OqNf/nyj+nxqR7rMY/FojJuobdZSBhJChnlMvA79
H7m8PpCRY/F9iXjQlGk5eoZ/bs9s2c3rbg==
-----END KTKDH_2Pass PEM File-----

**Comment by satur9nine** [comment]
You may want to purchase the latest copy of the standard from 2019. I don't have a copy of the older 2012 standard to work with so I'm not sure what differences there are between the two in this area if any.

Regardless you should study the test I mentioned `Tr34CloverTest#cloverGenerateTwoPassKeyToken` as well as `Tr34AscX9Test#ascSampleTwoPassKeyTokenParse` . In `Tr34AscX9Test#ascSampleTwoPassKeyTokenParse` notice the following line:

    Tr34TwoPassKeyToken resp = Tr34TwoPassKeyToken.create(AscSampleTr34Messages.SAMPLE_KDH_KT_2_PASS_FOR_KRD_1_CMS); 

This `create` method calls into the constructor of `Tr34TwoPassKeyToken` which parses ASN.1 of the two pass token into all the components you mentioned, see: https://github.com/clover/clover-tr34-host/blob/25e3ead11895b1cbc46e5dad76abdf3d61d51745/src/main/java/com/clover/tr34/Tr34TwoPassKeyToken.java#L71

I presume that you will likely be re-implementing the a parsing of  yourself which means you will need to study ASN.1 format and the structure of CMS messages as described in RFC 3369, see https://datatracker.ietf.org/doc/html/rfc3369

If you further follow `ascSampleTwoPassKeyTokenParse` you will see that you need the private key of the KRD, as well as the cert and chain of the KDH. Notice also that in the case of the 2019 ASC X9 samples the signature is rejected by BouncyCastle because the signed data is not ordered in a format that BouncyCastle strictly enforces per the CMS standard so I wrote a work-around to verify the the signature using the order that it was signed in; see `customCmsVerify`. At the end when trying to decrypt the ASC sample with BouncyCastle I ended up getting `Not a valid OAEP Parameter encoding` error which I never bothered to fully diagnose, but is clearly some problem related to the encryption of the ephemeral key.

I was able to get BouncyCastle to create a two pass token and decrypt that token as demonstrated in `Tr34CloverTest#cloverGenerateTwoPassKeyToken` test.

**Comment by cjh123456** [comment]
OK,Thanks,I'll try.

**Comment by cjh123456** [comment]
ASN1Sequence obj = ASN1Sequence.getInstance(enveloped.getOctets());

**Comment by cjh123456** [comment]
ASN1Sequence obj = ASN1Sequence.getInstance(enveloped.getOctets());
This throw Exception:
java.lang.IllegalArgumentException: failed to construct sequence from byte[]: Extra data detected in stream.
enveloped.getOctets()=0201003182019e3082019a020100304a3041310b300906035504061302555331153013060355040a130c545233342053616d706c6573311b301906035504031312545233342053616d706c65204341204b524402053400000007304506092a864886f70d0101073038300d06096086480165030402010500301806092a864886f70d010108300b0609608648016503040201300d06092a864886f70d0101090400048201002cbd086dc723286d97aa617c1e94980e539ae8bf51a926c55fe4858be480856506f08f009327e2eac813d77c7b24a0ae52325c56452f750466cd5781ef1cb4b573a60724106d1252f18c274229599b7887ba379c5081782198dc9a094493d389ca83d6f08d58d88e954806f7b00a620b20ca60790674727c79d74b79e039c985e2f107bec30a7fc82e5cd4268a1a2cd579fc822cc366a572dc699526a1b1cc0ce3f6830ae7feaa2be1464f1bfb4814d978f6007646407f224b75840f961127ef0e234726a36a36564a32d2c74605a50849c9bf9f93f727d1ac68fed720deeed2ad0a064b30ac01d2beeb3ccd03d46315d40f1ffd6d260dc6f6537d70e02818a73081ad06092a864886f70d01070130819f06082a864886f70d030704080123456789abcdef8081885332a1f84521de2d3b23ebe3cb2d674b16114ec598214102c3dee175c2a669400eb039136e632e4a32140aab5546ac478799f7b7a025335f45cca3cd1894314ff513e3e02573adb5135df8b1db3277d9de273dc6a8b5e79d215f63b93a52137dbafbe5cc3ff472919d86d2409762370fa80a77aed183e1ed597bf9bfdc9d286934c7c1e1e8d003fb

**Comment by satur9nine** [comment]
The bytes do not appear to be valid ASN.1 DER. I'm not sure how you created these bytes exactly so I cannot tell you what went wrong.

I'm not an expert on the DER format but I've noticed that ASN.1 sequences encoded to DER always start with byte 0x30. For example the random number token looks like this in hex:

```
echo "MCAGCiqGSIb3DQEJGQMxEgQQFn6w5yeB5JQBEiM0RVZneA==" | base64 -d | xxd
00000000: 3020 060a 2a86 4886 f70d 0109 1903 3112  0 ..*.H.......1.
00000010: 0410 167e b0e7 2781 e494 0112 2334 4556  ...~..'.....#4EV
00000020: 6778                                     gx
```

A helpful tool for working with ASN.1 is openssl. Here is an example showing how to decode a TR-34 random number token with openssl:
```
echo "MCAGCiqGSIb3DQEJGQMxEgQQFn6w5yeB5JQBEiM0RVZneA==" | base64 -d | openssl asn1parse --inform DER
    0:d=0  hl=2 l=  32 cons: SEQUENCE          
    2:d=1  hl=2 l=  10 prim: OBJECT            :1.2.840.113549.1.9.25.3
   14:d=1  hl=2 l=  18 cons: SET               
   16:d=2  hl=2 l=  16 prim: OCTET STRING      [HEX DUMP]:167EB0E72781E4940112233445566778
```
